version: "3.8"
name: "backend"
services:
  envoy:
    image: lamlance/trello-envoy:latest
    ports:
      - "80:10000"

  backend-cardlist:
    image: lamlance/trello-backend:cardlist-latest
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=cardlist

  backend-board:
    image: lamlance/trello-backend:board-latest
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=board

  backend-workspace:
    image: lamlance/trello-backend:workspace-latest
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=workspace
