name: Test e2e CI

on:
  push:
    branches: ["dev/*", "release/*", "main"]
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: cypress-io/github-action@v2
        with:
          start: npm run dev -w @trello-v2/user
      - name: Unit test backend cardlist
        run: npm run test cardlist -w @trello-v2/backend
