name: Test e2e CI

on:
  push:
    branches: ["dev/*", "release/*", "main"]
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install all depend
        run: npm i

      - name: Build shared packages
        working-directory: packages/shared
        run: npm run build

      - uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: Frontend/user
          start: npx vite --host

      - name: Unit test backend cardlist
        working-directory: Backend
        run: npm run test cardlist
