name: Test e2e CI

on:
  push:
    branches: ["dev/*", "release/*", "main"]
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: node_modules_cache

      - name: Install all depend
        run: npm install

      - name: Build shared packages
        working-directory: packages/shared
        run: |
          npm install
          npm run build

      - name: Install fontend depend
        working-directory: Frontend/user
        run: npm install

      - uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: Frontend/user
          start: npm run dev:host

      - name: Unit test backend cardlist
        run: npm run test cardlist -w @trello-v2/backend
