name: Test e2e CI

on:
  push:
    branches: ["dev/*", "release/*", "main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Unit test backend
        working-directory: ./Backend
        run: npm run test cardlist
      - name: E2e test front end
        working-directory: ./Frontend
        uses: cypress-io/github-action@v2
        with:
          dev: npm run dev
