name: Test e2e CI

on:
  push:
    branches: ["dev/*", "release/*", "main"]
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install all depend
        run: npm i

      - name: Build shared packages
        working-directory: packages/shared
        run: npm run build

      - name: Test cypress
        working-directory: Frontend/user
        run: |
          npm run test

      - name: Unit test backend cardlist
        working-directory: Backend
        run: npm run test cardlist
